---
vulnerabilities:
  - id: CVE-2024-45338
    paths:
      - "usr/local/bin/dockerd"
    expired_at: 2025-03-15
  - id: CVE-2024-45337
    paths:
      - "usr/local/bin/dockerd"
    expired_at: 2025-03-15
