---
vulnerabilities:
  - id: CVE-2025-22869
    paths:
      - "usr/local/libexec/docker/cli-plugins/docker-buildx"
      - "usr/local/libexec/docker/cli-plugins/docker-compose"
    expired_at: 2025-05-16
