---
vulnerabilities:
  - id: CVE-2024-45337
    paths:
      - "usr/lib/docker/cli-plugins/docker-buildx"
      - "usr/local/bin/dockerd"
      - "usr/local/libexec/docker/cli-plugins/docker-buildx"
      - "usr/local/libexec/docker/cli-plugins/docker-compose"
    statement: https://github.com/thegeeklab/wp-docker-buildx/issues/293
    expired_at: 2025-01-13
