---
vulnerabilities:
  - id: CVE-2025-61729
    expired_at: 2026-03-21
    paths:
      - "usr/lib/docker/cli-plugins/docker-buildx"
      - "usr/local/libexec/docker/cli-plugins/docker-buildx"

  - id: CVE-2025-52881
    expired_at: 2026-03-21
    paths:
      - "usr/local/bin/containerd"
      - "usr/local/bin/ctr"
