FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:fcae9e0e7313c6467a7c6632ebb5e5fab99bd39bd5eb6ee34a211353e647827a as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker:27.0-dind@sha256:2632da0d24924b179adf1c2e6f4ea6fb866747e84baea6b2ffaa8bff982ce102

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-docker-buildx"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-docker-buildx"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-docker-buildx"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-docker-buildx"

ARG TARGETOS
ARG TARGETARCH
ARG BUILDX_VERSION

# renovate: datasource=github-releases depName=docker/buildx
ENV BUILDX_VERSION="${BUILDX_VERSION:-v0.15.1}"

ENV DOCKER_HOST=unix:///var/run/docker.sock

RUN apk --update add --virtual .build-deps curl && \
    apk --update add --no-cache git coredns && \
    mkdir -p /usr/lib/docker/cli-plugins/ && \
    curl -SsL -o /usr/lib/docker/cli-plugins/docker-buildx \
        "https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION##v}/buildx-v${BUILDX_VERSION##v}.${TARGETOS:-linux}-${TARGETARCH:-amd64}" && \
    chmod 755 /usr/lib/docker/cli-plugins/docker-buildx && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/Corefile /etc/coredns/Corefile
COPY --from=build /src/dist/wp-docker-buildx /bin/wp-docker-buildx
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "wp-docker-buildx"]
